version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Org-EthereaLogic/devdocai-maintainers"
    assignees:
      - "Org-EthereaLogic/devdocai-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    groups:
      python-core:
        patterns:
          - "pydantic"
          - "click"
          - "sqlalchemy"
          - "cryptography"
      python-ai:
        patterns:
          - "openai"
          - "anthropic"
          - "google-generativeai"
      python-testing:
        patterns:
          - "pytest"
          - "coverage"
          - "black"
          - "pylint"
          - "mypy"

  # Node.js dependencies for development tooling
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Org-EthereaLogic/devdocai-maintainers"
    assignees:
      - "Org-EthereaLogic/devdocai-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "typescript"
    groups:
      typescript-core:
        patterns:
          - "typescript"
          - "@types/*"
      testing-tools:
        patterns:
          - "jest"
          - "@types/jest"
      linting-tools:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
