---
# Codacy configuration file
# Exclude legacy and backup directories from analysis

engines:
  duplication:
    enabled: true
    exclude_paths:
      - "**/legacy_backup/**"
      - "**/*_backup/**"
      - "**/legacy/**"
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/.git/**"
      - "**/coverage/**"
      - "**/__pycache__/**"
      - "**/*.pyc"
      - "**/test_*.py"
      - "**/debug_*.py"
      - "**/profile_*.py"
      - "**/simple_*.py"
      - "**/final_*.py"
  
  metrics:
    enabled: true
    exclude_paths:
      - "**/legacy_backup/**"
      - "**/*_backup/**"
      - "**/legacy/**"
  
  coverage:
    enabled: true
    exclude_paths:
      - "**/legacy_backup/**"
      - "**/*_backup/**"
      - "**/legacy/**"
      - "**/tests/**"
      - "**/test_*.py"

exclude_paths:
  - "**/legacy_backup/**"
  - "**/*_backup/**"  
  - "**/legacy/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/.git/**"
  - "**/coverage/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/test_*.py"
  - "**/debug_*.py"
  - "**/profile_*.py"
  - "**/simple_*.py"
  - "**/final_*.py"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/vendor/**"
  - "**/migrations/**"
  - "**/*.lock"
  - "**/*.log"