privacy_mode: LOCAL_ONLY
telemetry_enabled: false
llm:
  provider: anthropic
  api_key: your_api_key_here  # pragma: allowlist secret
  model: claude-3-5-sonnet-20241222
  max_tokens: 4000
  temperature: 0.7
