name: Quick Check
permissions:
  contents: read

# This workflow runs on every push for fast feedback
on:
  push:
    branches-ignore:
      - main

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    # Use standard checkout action
    - uses: actions/checkout@v5
    
    # Single Python version for speed
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # Quick dependency install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Run basic checks
    - name: Run basic checks
      run: |
        # Check Python syntax
        python -m py_compile devdocai/**/*.py 2>/dev/null || echo "No Python files yet"
        
        # Run quick tests if they exist
        if [ -d "tests" ]; then
          python -m pytest tests/ -x --tb=short || true
        fi
        
        # Check if environment test passes
        if [ -f "test_environment.py" ]; then
          python test_environment.py
        fi